### ISSUE TITLE
php requirement

### ISSUE THREAD

**Issue by goatherd** [reneoelke/Php54to55#15]
You set a `>= 5.5` for PHP dependency. But it does work with composer dependency (5.3.x) with the only issue being unsupported `trait`, `callable`, `instanceof` and `finally` keywords.

I would rather have a `E_NOTICE` or `E_USER_WARNING` issued by the ReservedKeywordSniff or a notice/ message issued by the binary.

The trouble arising with a high requirement is the increase with each new PHP release.
We never talked about this but may want to now:
- do we support only the most recent PHP tokenizer
- or do we skip a subset for older tokenizers

This may effect handling of distinct PHP interpreters like HHVM if we decide to test against those (as codesniffer itself does).

**Comment by reneoelke** [comment]
Minimum requirement should be changed to PHP 5.3. You can fix the README.
